<a href="https://colab.research.google.com/github/SaeidAbdolian/Mini-projects-of-images-processing/blob/main/Gaossian-filter/steps_of_making_Gaussian_filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

steps of making gaussian matrix according to size of matrix


<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQrYYm-8YHahikqrlLtLzKhPJJW4Wn04D1Ow&usqp=CAU"> 

and

<img src="https://lib.znate.ru/pars_docs/refs/100/99949/99949_html_m5c652835.gif" >

In [ ]:

xx = np.arange(0, 7, 1, float)
print(xx)
print()
yy = xx[:, np.newaxis]
print(yy)
print()
print(xx - 3.5)
print()
print(yy - 3.5)
print()
print(xx*xx)
print()
print(yy*yy)
print()
print(xx*xx+yy*yy)
print()
print((xx*xx+yy*yy)/ (2. * 7 * 7))
print()
print(np.exp(-((xx*xx+yy*yy)/ (2. * 7 * 7))))
print()
print((np.exp(-((xx*xx+yy*yy)/ (2. * 7 * 7))))/np.sum(np.exp(-((xx*xx+yy*yy)/ (2. * 7 * 7)))))

[0. 1. 2. 3. 4. 5. 6.]

[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]]

[-3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5]

[[-3.5]
 [-2.5]
 [-1.5]
 [-0.5]
 [ 0.5]
 [ 1.5]
 [ 2.5]]

[ 0.  1.  4.  9. 16. 25. 36.]

[[ 0.]
 [ 1.]
 [ 4.]
 [ 9.]
 [16.]
 [25.]
 [36.]]

[[ 0.  1.  4.  9. 16. 25. 36.]
 [ 1.  2.  5. 10. 17. 26. 37.]
 [ 4.  5.  8. 13. 20. 29. 40.]
 [ 9. 10. 13. 18. 25. 34. 45.]
 [16. 17. 20. 25. 32. 41. 52.]
 [25. 26. 29. 34. 41. 50. 61.]
 [36. 37. 40. 45. 52. 61. 72.]]

[[0.         0.01020408 0.04081633 0.09183673 0.16326531 0.25510204
  0.36734694]
 [0.01020408 0.02040816 0.05102041 0.10204082 0.17346939 0.26530612
  0.37755102]
 [0.04081633 0.05102041 0.08163265 0.13265306 0.20408163 0.29591837
  0.40816327]
 [0.09183673 0.10204082 0.13265306 0.18367347 0.25510204 0.34693878
  0.45918367]
 [0.16326531 0.17346939 0.20408163 0.25510204 0.32653061 0.41836735
  0.53061224]
 [0.25510204 0.26530612 0.29591837 0.34693878 0.41836735 0.51020408
  0.62244898]
 [0.36734694 0.37755102 0.40816327 0.459183